# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOS Club' do
  use_frameworks!

  pod 'SnapKit'
  pod 'Gallery', :git => 'https://github.com/hyperoslo/Gallery.git', :branch => 'master'
  pod 'BMPlayer'
  pod 'VACalendar'
  pod 'SkeletonView'
  pod 'LLCycleScrollView'
  pod 'Alamofire', '~> 4.7'
  pod 'SwiftyJSON', '~> 4.0'

end
