# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Club Share' do
  use_frameworks!
    
  pod 'Alamofire', '~> 4.7'
    
end


target 'iOS Club' do
  use_frameworks!

  pod 'Hue'
  pod 'SnapKit'
  pod 'Gallery', :git => 'https://github.com/hyperoslo/Gallery.git', :branch => 'master'
  pod 'BMPlayer'
  pod 'Lightbox'
  pod 'LGButton'
  pod 'VACalendar'
  pod 'WSTagsField'
  pod 'SkeletonView'
  pod 'SVProgressHUD'
  pod 'SKPhotoBrowser'
  pod 'URLEmbeddedView'
  pod 'TextFieldEffects'
  pod 'LLCycleScrollView'
  pod 'Alamofire', '~> 4.7'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'IQKeyboardManagerSwift'
  pod 'NotificationBannerSwift'

end
